-- APT-to-PDF pipeline schema (architecture diagram)
-- MTB_APT: JOB_MASTER, JOB_SCHEDULE, PROCESS_LOG, ERROR_LOG, FILE_METADATA

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'MTB_APT')
    EXEC('CREATE SCHEMA MTB_APT');

IF OBJECT_ID('MTB_APT.JOB_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE MTB_APT.JOB_MASTER (
        JobName NVARCHAR(100) NOT NULL PRIMARY KEY,
        Description NVARCHAR(500) NULL,
        CreatedAtUtc DATETIME2(3) NOT NULL CONSTRAINT DF_MTB_APT_JOB_MASTER_CreatedAtUtc DEFAULT SYSUTCDATETIME()
    );
END;

IF OBJECT_ID('MTB_APT.JOB_SCHEDULE', 'U') IS NULL
BEGIN
    CREATE TABLE MTB_APT.JOB_SCHEDULE (
        JobName NVARCHAR(100) NOT NULL PRIMARY KEY,
        Frequency NVARCHAR(50) NOT NULL,
        RunTime TIME(0) NULL,
        NextRunTimeUtc DATETIME2(3) NOT NULL,
        Enabled BIT NOT NULL CONSTRAINT DF_MTB_APT_JOB_SCHEDULE_Enabled DEFAULT 1,
        Status NVARCHAR(20) NOT NULL CONSTRAINT DF_MTB_APT_JOB_SCHEDULE_Status DEFAULT 'Idle',
        UpdatedAtUtc DATETIME2(3) NOT NULL CONSTRAINT DF_MTB_APT_JOB_SCHEDULE_UpdatedAtUtc DEFAULT SYSUTCDATETIME()
    );
END;

IF OBJECT_ID('MTB_APT.PROCESS_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE MTB_APT.PROCESS_LOG (
        Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JobName NVARCHAR(100) NOT NULL,
        FileName NVARCHAR(260) NOT NULL,
        Status NVARCHAR(20) NOT NULL,
        Attempts INT NOT NULL,
        OutputBlobName NVARCHAR(500) NULL,
        Message NVARCHAR(2000) NULL,
        ProcessedAtUtc DATETIME2(3) NOT NULL CONSTRAINT DF_MTB_APT_PROCESS_LOG_ProcessedAtUtc DEFAULT SYSUTCDATETIME()
    );
END;

IF OBJECT_ID('MTB_APT.ERROR_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE MTB_APT.ERROR_LOG (
        Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JobName NVARCHAR(100) NOT NULL,
        FileName NVARCHAR(260) NOT NULL,
        Attempts INT NOT NULL,
        ErrorMessage NVARCHAR(2000) NOT NULL,
        Details NVARCHAR(MAX) NULL,
        LoggedAtUtc DATETIME2(3) NOT NULL CONSTRAINT DF_MTB_APT_ERROR_LOG_LoggedAtUtc DEFAULT SYSUTCDATETIME()
    );
END;

IF OBJECT_ID('MTB_APT.FILE_METADATA', 'U') IS NULL
BEGIN
    CREATE TABLE MTB_APT.FILE_METADATA (
        Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        SourceFileName NVARCHAR(260) NOT NULL,
        SourceBlobPath NVARCHAR(500) NOT NULL,
        OutputBlobName NVARCHAR(500) NOT NULL,
        ArchiveBlobName NVARCHAR(500) NOT NULL,
        FileType NVARCHAR(50) NOT NULL,
        FileSizeBytes BIGINT NULL,
        Status CHAR(1) NOT NULL,
        ProcessedAtUtc DATETIME2(3) NOT NULL CONSTRAINT DF_MTB_APT_FILE_METADATA_ProcessedAtUtc DEFAULT SYSUTCDATETIME()
    );
END;

IF NOT EXISTS (SELECT 1 FROM MTB_APT.JOB_MASTER WHERE JobName = 'APT_TO_PDF')
    INSERT INTO MTB_APT.JOB_MASTER (JobName, Description)
    VALUES ('APT_TO_PDF', 'APT-to-PDF batch pipeline');

IF NOT EXISTS (SELECT 1 FROM MTB_APT.JOB_SCHEDULE WHERE JobName = 'APT_TO_PDF')
    INSERT INTO MTB_APT.JOB_SCHEDULE (JobName, Frequency, RunTime, NextRunTimeUtc, Enabled, Status)
    VALUES ('APT_TO_PDF', 'Daily', '20:00:00', SYSUTCDATETIME(), 1, 'Idle');

-- Change schedule without redeploying:
-- UPDATE MTB_APT.JOB_SCHEDULE SET RunTime = '20:00:00', NextRunTimeUtc = '2026-07-10T20:00:00Z', Enabled = 1 WHERE JobName = 'APT_TO_PDF';
